### PR TITLE
[fix] Rename ROCKWNODE to ROCKWNOD as it should be.

### LINKED ISSUE #195: ROCKWNODE keyword should be ROCKWNOD
The file ROCKWNODE.fodt should be ROCKWNOD.fodt, and the keyword name should be changed from ROCKWNODE to ROCKWNOD in the manual.
Can the keyword and file names be changed without breaking anything?

### PR DESCRIPTION
**Pull request by blattms**
Closes #195

### CODE REVIEW

**Review by gdfldm — COMMENTED** [review]
I can't find the new file ROCKWNOD.fodt?

**Review by gdfldm — APPROVED** [review]
These changes look good to me.

**Comment by blattms** [comment]
> I can't find the new file ROCKWNOD.fodt?

Thanks for noticing. I missed that one and also the meta-information in keyword-names. Now it should work. Maybe @hakonhagland should take another look and merge.

**Review by hakonhagland — APPROVED** [review]
Thanks, this looks good!

**Pull request merged**
