### PR TITLE
Fixed footer style for letter "I" in all .fodt files

### PR DESCRIPTION
**Pull request by hakonhagland**
Builds on #188 which should be merged first.

See #179 for background.

### CODE REVIEW

**Comment by blattms** [comment]
Sorry for the conflicts. I hope this can be rebased easily.

**Comment by hakonhagland** [comment]
> Sorry for the conflicts. I hope this can be rebased easily.

@blattms No problem!  I will rebase this after #174 has been merged.

**Comment by blattms** [comment]
Thanks, I just merged the other one.

**Comment by hakonhagland** [comment]
@blattms Rebased.

**Comment by blattms** [comment]
I think we missed something here:

- style name should be the same as for H (e.g. P1202 instead of P1206, P12 instead of P13, T1 instead of T5,... )

 I did that now in 01f5a1fc6b8d3b7f3f13708e2c85eef1f960f61c of #211 for main.fodt, which suffices when looking at the whole document,

**Comment by hakonhagland** [comment]
@blattms Looking at main.fodt, the only difference I can see between P1202 and P1206 is that P1206 has attributes `fo:language="en"` and `fo:country="US"`. Do you know what those attributes are used for?

Here is what I see in main.fodt:
```
  <style:style style:name="P1202" style:family="paragraph" style:parent-style-name="Table_20_Contents">
   <style:paragraph-properties fo:text-align="center" style:justify-single-word="false"/>
   <style:text-properties fo:color="#000000" loext:opacity="100%" fo:font-size="9pt" style:font-size-asian="9pt" style:font-size-complex="9pt"/>
  </style:style>
```
and for P1206
```
  <style:style style:name="P1206" style:family="paragraph" style:parent-style-name="Table_20_Contents">
   <style:paragraph-properties fo:text-align="center" style:justify-single-word="false"/>
   <style:text-properties fo:color="#000000" loext:opacity="100%" fo:font-size="9pt" fo:language="en" fo:country="US" style:font-size-asian="9pt" style:font-size-complex="9pt"/>
```

**Comment by blattms** [comment]
I don't now. Maybe it is the missing style T1
```diff
-       <text:p text:style-name="P1206"><text:bookmark-ref text:reference-format="text" text:ref-name="I"><text:span text:style-name="Internet_20_link">I</text:span></text:bookmark-ref></text:p>
+       <text:p text:style-name="P1202"><text:span text:style-name="Internet_20_link"><text:span text:style-name="T1"><text:bookmark-ref text:reference-format="text" text:ref-name="I">I</text:bookmark-ref></text:span></text:span></text:p>
```
or the order of the spans?

**Comment by hakonhagland** [comment]
> Maybe it is the missing style T1

@blattms Yes, but in main.fodt T1 is defined like this:

```
 <style:style style:name="T1" style:family="text">
   <style:text-properties fo:language="en" fo:country="US"/>
  </style:style>
```
So it only introduces the `fo:language="en"` and `fo:country="US"` attributes but these attributes were exactly those attributes that P1206 added compare to P1202, right? So the missing T1 should not be an issue. What issues do you see in your document? Can you share a screenshot

**Comment by gdfldm** [comment]
> or the order of the spans?

I have tested changing the order of the nesting for H to...

```
      <table:table-cell table:style-name="Table109.A1" office:value-type="string">
       <text:p text:style-name="P1202"><text:bookmark-ref text:reference-format="text" text:ref-name="H"><text:span text:style-name="Internet_20_link"><text:span text:style-name="T1">H</text:span></text:span></text:bookmark-ref></text:p>
      </table:table-cell>
```

..and this reproduces the formatting issue:

image

**Comment by hakonhagland** [comment]
@gdfldm Thanks for testing. The screenshot shows how "I" is formatted in the current version of main.fodt, right?

**Comment by gdfldm** [comment]
> the current version of main.fodt, right?

Strictly it's my fork of the current version but it is up to date.

**Comment by hakonhagland** [comment]
> The screenshot shows how "I" is formatted in the current version of main.fodt, right?

@gdfldm I am no longer able to open main.fodt so I cannot check..

**Comment by gdfldm** [comment]
> no longer able to open main.fodt

I will try opening using LO on win11 and check the formatting

**Comment by hakonhagland** [comment]
@gdfldm And this is only observed when opening main.fodt? I can open chapters/10.fodt and I cannot see the issue there

**Comment by gdfldm** [comment]
> And this is only observed when opening main.fodt?

I just open 10.fodt and formatting looks fine. But there appear to be no links and the K has been replaced by an E?

image

**Comment by hakonhagland** [comment]
> But there appear to be no links

@gdfldm Yes, I think we removed the links for the sub documents, see e.g. https://github.com/OPM/opm-reference-manual/pull/29

> the K has been replaced by an E?
@gdfldm Yes. I think we might need a script to fix this.. I guess it needs to fixed in all sub documents?

**Comment by hakonhagland** [comment]
> the K has been replaced by an E?

@gdfldm Strange. I think I remember we fixed the E letter in https://github.com/OPM/opm-reference-manual/pull/68

**Comment by hakonhagland** [comment]
Seems like it was only done for main.fodt, not for the sub documents

**Comment by gdfldm** [comment]
It appears that when main.fodt is opened the E in the sub documents is replaced by the correct K from main.fodt so not a problem. But would be nice to fix it in the sub documents.

**Pull request merged**
