### PR TITLE
Add SOURCE keyword to SCHEDULE section for 2024-04

### PR DESCRIPTION
**Pull request by gdfldm**
fodt-add-keyword --keyword SOURCE --section 12.3 --title "Define Source Term" --status green --appendix

### CODE REVIEW

**Comment by hakonhagland** [comment]
@gdfldm Yes I will check now :)

**Comment by hakonhagland** [comment]
There seem to be an issue with the link to SGU in appendix A also:

image

when I click on I end up in SGOF in chapter 8 (instead of in the SGU section in chapter 8)

**Comment by hakonhagland** [comment]
I believe #284 and #285 should solve this issue. I am not able to load main.fodt on my machine, so hope you check that this is the case @gdfldm

**Comment by gdfldm** [comment]
> I believe #284 and #285 should solve this issue. I am not able to load main.fodt on my machine, so hope you check that this is the case @gdfldm

@hakonhagland. Many thanks. Will do :)

**Comment by gdfldm** [comment]
Just looking at A.fodt the SOURCE keyword is now in the correct position :)

But when I try to mark it as an OPM Flow keyword with:
```fodt-set-keyword-status --keyword SOURCE --color green --opm-flow```
I get:
```
INFO:root:Updating parameters for keyword SOURCE:  Color: KeywordStatus.GREEN, flow-specific keyword: True.
INFO:root:Found office:body.
INFO:root:Found 38 orange styles.
INFO:root:Using orange style Table47.H7.
INFO:root:Found 29 green styles.
INFO:root:Using green style Table45.H6.
INFO:root:Keyword SOURCE not found in ..\..\parts\appendices\A.fodt.
```
Perhaps it's the regex again?

**Comment by hakonhagland** [comment]
> Perhaps it's the regex again?

@gdfldm Indeed, thanks :) See #287.

**Comment by hakonhagland** [comment]
Sorry, I did not see that you already merged the change. Will rebase this one.

**Pull request closed without merging**
