### PR TITLE
Fix table reference inAppendix C.2.5

### PR DESCRIPTION
**Pull request by gdfldm**
~There is still a reference to the section containing the table.
There doesn't seem to be a simple way to reference a table in a different sub-document.~

Fixed table ref

### CODE REVIEW

**Comment by blattms** [comment]
This will need  a rebase, too. Maybe we should rebase one at  a time...

**Comment by gdfldm** [comment]
Okay, I have rebased #339, and will wait for that to be merged before rebasing this PR.

Thanks for all the merges :)

**Comment by blattms** [comment]
Time for a rebase?

**Comment by gdfldm** [comment]
> Time for a rebase?

Thanks for the reminder :)

**Pull request merged**
