### PR TITLE
Simplifed docker scripts helper functions 

### PR DESCRIPTION
**Pull request by hakonhagland**

### CODE REVIEW

**Comment by hakonhagland** [comment]
@lisajulia I ran the docker test files with this PR and all tests passed on my machine. Can you have a look at this? If it works for you, we can also merge #424.

**Comment by lisajulia** [comment]
> @lisajulia I ran the docker test files with this PR and all tests passed on my machine. Can you have a look at this? If it works for you, we can also merge #424.

I quickly tried that locally as well, and I got this error:

```
(python-venv) lnebel@thinkpad-x1-lisa:~/git_repos/opm/opm-reference-manual$ cd docker/
(python-venv) lnebel@thinkpad-x1-lisa:~/git_repos/opm/opm-reference-manual/docker$ poetry run pytest tests
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.11.2, pytest-8.0.1, pluggy-1.4.0
rootdir: /home/lnebel/git_repos/opm/opm-reference-manual/docker
plugins: mock-3.12.0
collected 1 item / 1 error                                                                                                                                                                                        

===================================================================================================== ERRORS ======================================================================================================
____________________________________________________________________________________ ERROR collecting tests/test_user_input.py ____________________________________________________________________________________
tests/test_user_input.py:4: in <module>
    user_input = helpers.user_input
E   AttributeError: module 'lodocker.helpers' has no attribute 'user_input'
============================================================================================= short test summary info =============================================================================================
ERROR tests/test_user_input.py - AttributeError: module 'lodocker.helpers' has no attribute 'user_input'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================================ 1 error in 0.06s =================================================================================================
```
I don't know if I am doing sth. wrong here ... :thinking:

**Comment by hakonhagland** [comment]
> $ poetry run pytest tests
tests/test_user_input.py:4: in <module>
    user_input = helpers.user_input
E   AttributeError: module 'lodocker.helpers' has no attribute 'user_input'

@lisajulia Yes that is strange. When I run the same command on my machine I get:

```
$ poetry run pytest tests
==================================================================== test session starts =====================================================================
platform linux -- Python 3.12.0, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/hakon/opm-reference-manual/docker
plugins: mock-3.12.0
collected 12 items                                                                                                                                           

tests/test_find_git_root.py .                                                                                                                          [  8%]
tests/test_user_input.py ...........                                                                                                                   [100%]

===================================================================== 12 passed in 0.02s =====================================================================
```

The error message you showed says: `tests/test_user_input.py:4 ...`. Line 4 is [this](https://github.com/OPM/opm-reference-manual/pull/425/files#diff-1e2b4139b5a90ba97a217d7a998af2a7bb67f849b15d2cd350944bf1b7428c01R4) line, and it refers to a function `lodocker.helpers.user_input` that it cannot find. However, the function is defined [here](https://github.com/OPM/opm-reference-manual/pull/425/files#diff-64110b8e489f4f09e5b3500e8327f0c102595e73da4394779076f07e241a1796R104) in the file `src/lodocker/helpers.py`.

Can you check if your local branch contains that function also?

**Comment by lisajulia** [comment]
> > $ poetry run pytest tests
> > tests/test_user_input.py:4: in 
> > user_input = helpers.user_input
> > E   AttributeError: module 'lodocker.helpers' has no attribute 'user_input'
> 
> @lisajulia Yes that is strange. When I run the same command on my machine I get:
> 
> ```
> $ poetry run pytest tests
> ==================================================================== test session starts =====================================================================
> platform linux -- Python 3.12.0, pytest-8.0.0, pluggy-1.4.0
> rootdir: /home/hakon/opm-reference-manual/docker
> plugins: mock-3.12.0
> collected 12 items                                                                                                                                           
> 
> tests/test_find_git_root.py .                                                                                                                          [  8%]
> tests/test_user_input.py ...........                                                                                                                   [100%]
> 
> ===================================================================== 12 passed in 0.02s =====================================================================
> ```
> 
> The error message you showed says: `tests/test_user_input.py:4 ...`. Line 4 is [this](https://github.com/OPM/opm-reference-manual/pull/425/files#diff-1e2b4139b5a90ba97a217d7a998af2a7bb67f849b15d2cd350944bf1b7428c01R4) line, and it refers to a function `lodocker.helpers.user_input` that it cannot find. However, the function is defined [here](https://github.com/OPM/opm-reference-manual/pull/425/files#diff-64110b8e489f4f09e5b3500e8327f0c102595e73da4394779076f07e241a1796R104) in the file `src/lodocker/helpers.py`.
> 
> Can you check if your local branch contains that function also?

It works now :) - I thought I had run poetry install, but apparently not - running it again fixed it - sorry about that!

**Pull request merged**
