### PR TITLE
Fix add keyword

### PR DESCRIPTION
**Pull request by hakonhagland**
This PR builds on #212, which should be merged first.

For background see #228. Updated the add-keyword script to handle empty tags.

### CODE REVIEW

**Comment by blattms** [comment]
Does this also automatically apply to add_keyword_status.py?

**Comment by hakonhagland** [comment]
> Does this also automatically apply to add_keyword_status.py?

@blattms No, but the set-keyword-status script was fixed to handle empty tags in #227 I believe

**Comment by hakonhagland** [comment]
@lisajulia Sure!

**Review by lisajulia — APPROVED** [review]
Looks good to me; I've tested this as well.

**Pull request merged**
