### PR TITLE
Mark ROCKTAB as supported

### PR DESCRIPTION
**Pull request by gdfldm**
in keyword description and appendix a
Addresses #219

### CODE REVIEW

**Comment by blattms** [comment]
I guess @gdfldm  has used our scripts for this.  @hakonhagland, might the add_keyword_status.py mess up the diff due changing xml-end-tags?

**Comment by hakonhagland** [comment]
> might the add_keyword_status.py mess up the diff due changing xml-end-tags?

@blattms Yes you are right, it would. I think the end tags was fixed in https://github.com/OPM/opm-reference-manual/pull/227 but that is not merged yet.

**Comment by gdfldm** [comment]
> who did you perform these changes? With scripts?

@blattms I used the script to update Appendix A. Then edited the XML for ROCKTAB.fodt.

**Comment by gdfldm** [comment]
replaced by #237

**Pull request closed without merging**
