### PR TITLE
Renamed `scripts/` to `scripts/python`

### PR DESCRIPTION
**Pull request by hakonhagland**
For background see #146.

### CODE REVIEW

**Comment by blattms** [comment]
@lisajulia Is this closed on purpose?

**Comment by blattms** [comment]
Seems like as it has to be rebased now.

**Comment by lisajulia** [comment]
I merged this one: https://github.com/OPM/opm-reference-manual/pull/150 ... so possibly because of the merge this one here has to be rebased - but actually still don't know why this PR is closed now

**Comment by lisajulia** [comment]
@hakonhagland: I can't reopen this PR - can you?

**Comment by hakonhagland** [comment]
> I can't reopen this PR - can you?

@lisajulia No I can't. I will resubmit it later

**Comment by hakonhagland** [comment]
Resubmitted this as #151

**Pull request closed without merging**
