### PR TITLE
Updated README.md with information about disabling document comparison option

### PR DESCRIPTION
**Pull request by hakonhagland**
See https://github.com/OPM/opm-reference-manual/pull/203#discussion_r1523537605 for background.

Added information about disabling document comparison option in LibreOffice to make editing documents easier.

### CODE REVIEW

**Comment by blattms** [comment]
This is of course  a global setting in libreoffice and people might not want to have this elsewhere.

**Comment by hakonhagland** [comment]
@blattms Yes I did not think about that. Maybe we could make the docker version use this setting by default? Since the docker version of libreoffice will only be used for editing the opm-reference-manual files and the docker container will have its own settings (separate from the host machine settings)

**Comment by blattms** [comment]
I added a suggested change. With that I would merge this anyway.

**Comment by hakonhagland** [comment]
@blattms Thanks! Updated.

**Comment by blattms** [comment]
Cool. Thanks a lot.

**Pull request merged**
