### PR TITLE
 Correct numerous typos and inconsistencies in manual (part 2)

### PR DESCRIPTION
**Pull request by pkirkham**
A second set of changes that I've been accumulating whilst going through the manual.

### CODE REVIEW

**Comment by pkirkham** [comment]
Looks like there are some conflicts, probably due to changes in the underlying documents whilst I was making changes on my local copies. Hopefully it's not too hard to merge.

**Comment by blattms** [comment]
I thinks the problems are due @hakonhagland's  PR #174 I will try to rebase this one and create a PR from that. After that we need to rerun his script.

**Comment by hakonhagland** [comment]
> Looks like there are some conflicts, probably due to changes in the underlying documents whilst I was making changes on my local copies.

@pkirkham When was the last time you rebased this branch with main? I downloaded it and it seems to me it was rebased last one month ago onto this commit: https://github.com/OPM/opm-reference-manual/commit/3f188bed16b34e3a423a673c6515ee46f8ef3e6e

**Comment by pkirkham** [comment]
> @pkirkham When was the last time you rebased this branch with main? I downloaded it and it seems to me it was rebased last one month ago onto this commit: [3f188be](https://github.com/OPM/opm-reference-manual/commit/3f188bed16b34e3a423a673c6515ee46f8ef3e6e)

I started working on putting changes into these files after I did the first pull request test on 19 Feb 2024 (#157). I'm still learning how to use GitHub properly, so I might not have used the correct workflow. I'm not sure if my local copy updates or not depending on changes to main. It's probably still the version from 19 Feb that I was working on.

I guess in the worst case scenario, if this can't be merged easily enough, I can just make another fork and re-enter all the changes and then resubmit the PR?

**Comment by hakonhagland** [comment]
> if this can't be merged easily enough, I can just make another fork and re-enter all the changes and then resubmit the PR?

@pkirkham I think @blattms is working on rebasing this in #203. Let's see how that turns out first :+1: 

> I'm still learning how to use GitHub properly, so I might not have used the correct workflow. 

Yes, if you create a branch it will at some point diverge from the main branch if you do not rebase it. In this case it seems like it was too far from the main branch to be easily rebased? It is easier to rebase if you do it regularly (after each change in the main branch to the files you are working on in your branch)

**Pull request closed without merging**
