### PR TITLE
Fix letter "I" in the footer of main.fodt

### PR DESCRIPTION
**Pull request by hakonhagland**
For background see #189.

@gdfldm Can you check if this fixes the style of letter "I" in the footer of main.fodt?

### CODE REVIEW

**Comment by gdfldm** [comment]
Sorry, I'm not sure how to get your version of main.fodt before it is merged?

**Comment by hakonhagland** [comment]
@gdfldm You try something like this:

```
# save your current branch content (e.g. git add, git commit), then:
$ git checkout main
$ git fetch origin pull/215/head:pr215
$ git checkout pr215
# Now you have this version of main.fodt
```

**Comment by gdfldm** [comment]
I am using github desktop on win11. With a clone of OPM/opm-reference-manual I have selected pr/215 as the current branch then clicked Pull github-desktop-hakonhagland but then I get
image
should I try and do this?

**Comment by hakonhagland** [comment]
> should I try and do this?

I don't think so. It does not look right to me. First,

>  Pull github-desktop-hakonhagland

what is "github-desktop-hakonhagland" ?

**Comment by gdfldm** [comment]
> what is "github-desktop-hakonhagland" ?

This is what github desktop suggests:

image

**Comment by hakonhagland** [comment]
I am not familar with GitHub desktop so I will investigate a little bit. In the mean time, you could maybe try close it down and work from PowerShell and execute the commands there? Then reopen GitHub desktop after you have checkout the pr branch?

**Comment by hakonhagland** [comment]
> In the mean time, you could maybe try close it down and work from PowerShell and execute the commands there?

If you only have installed GitHub Desktop, maybe you need to install "Git for Windows" before you can work with git from the command line (in PowerShell) ? I will check on my Windows laptop

**Comment by hakonhagland** [comment]
Thanks for testing! I was thinking maybe GitHub desktop did not support directly checking out a PR from an upstream repository and that you would need to use the command line to do it. But seems like you managed to do it within GitHub desktop then?

**Comment by gdfldm** [comment]
I was able to do it with github desktop using my fork, but the clone of the main repo seemed to be a problem.

**Pull request merged**
