### PR TITLE
Replacement for PR #148

### PR DESCRIPTION
**Pull request by hakonhagland**
For some reason GitHub seems to have forgot about the opm-reference-manual remote, so I needed to refork it, but then it also lost all branch info. That is why I am resubmitting #148 here.

### CODE REVIEW

**Review by lisajulia — APPROVED** [review]
Looks good to me now :)

**Comment by lisajulia** [comment]
@hakonhagland: If you are done moving https://github.com/OPM/opm-reference-manual/pull/148 to here, then I'll merge this PR.

**Comment by hakonhagland** [comment]
Yes I think you can merge it now

**Comment by blattms** [comment]
> For some reason GitHub seems to have forgot about the opm-reference-manual remote, so I needed to refork it

Strange. I only made the repository public this morning.

**Comment by blattms** [comment]
Indeed all forks are gone. I am 100% sure that I had one.

**Pull request merged**
